---
- name: Verify version downgrade impact
  hosts: mlsmn013wkrm10
  connection: local
  gather_facts: false

  tasks: 
   - name: show downgrade impact
     check_mode: no
     nxos_command:
       commands: show install all impact nxos bootflash:n9000-dk9.6.1.2.I3.2.bin
       timeout: 300

     register: print_output

   - debug: var=print_output.stdout_lines

   - pause:
       minutes: 3

- name: Downgrade N9K Code n9000-dk9.6.1.2.I3.2.bin
  hosts: mlsmn013wkrm10
  connection: local
  gather_facts: false

  tasks: 
   - name: Install OS on N9k
     check_mode: no
     nxos_install_os:
       system_image_file: n9000-dk9.6.1.2.I3.2.bin
       issu: desired

     register: print_output

   - debug: var=print_output.stdout_lines

   - pause:
       minutes: 3

   - name: Check installed OS for downgraded version
     nxos_command:
       commands: ['show version | json']
     register: output
   - assert:
       that:
       - output['stdout'][0]['kickstart_ver_str'] == '6.1(2)I3(2)'
