---
- name: Backout Template 2, Downgrade N9K Code 
  hosts: mlsmn013wkrm10
  connection: network_cli
  gather_facts: false
  vars:
    ansible_network_os: nxos
    backout_9k_version: nxos.7.0.3.I3.1.bin
    backout_show_ver_value: 7.0(3)I3(1)

  tasks: 
   - name: Install OS on N9k
     check_mode: no
     nxos_install_os:
       system_image_file: "{{backout_9k_version}}"
       issu: desired

   - name: Wait for device to go down 
     wait_for:
       port: 22
       state: stopped
       timeout: 800
            
   - name: Wait for device to come back up 
     wait_for_connection:
       delay: 300
       timeout: 800
       
