---
- name: Generate Interface report
  hosts: cisco
  gather_facts: no
  connection: network_cli


  roles:
    - ansible-network.network-engine

  tasks:
    - name: capture show interfaces
      ios_command:
        commands:
          - show interfaces
      register: output
    - name: parse the raw output
      command_parser:
        file: "parsers/show_interfaces.yaml"
        content: "{{ output.stdout[0] }}"


    - name: DISPLAY THE PARSED DATA
      debug:
        var: interface_facts

    - name: GENERATE REPORT FRAGMENTS
      template:
        src: interface_facts.j2
        dest: intf_reports/{{inventory_hostname}}_intf_report.md

    - name: GENERATE A CONSOLIDATED REPORT
      assemble:
        src: intf_reports/
        dest: interfaces_report.md
      delegate_to: localhost
      run_once: yes
      
